### Create Post
POST {{host}}/posts
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token}}

--boundary
Content-Disposition: form-data; name="text"

post text
--boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="img.png"

< ./img.png

### Read Post
GET {{host}}/posts/1
Content-Type: application/json

### Update Post
PUT {{host}}/posts
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token}}

--boundary
Content-Disposition: form-data; name="text"

update text
--boundary

--boundary
Content-Disposition: form-data; name="id"

3
--boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="img.png"

< ./img.png

### Delete Post
DELETE {{host}}/posts/5
Content-Type: application/json
Authorization: Bearer {{token}}

### Shorten url by Post ID
POST {{host}}/posts/shorten/5
Content-Type: application/json

### Get by shortened url
GET localhost:8080/short/xO4nE8
Content-Type: application/json